### ISSUE TITLE
Analyse der Dependency Rule (Clean architecture Schichten)

### ISSUE THREAD

**Issue by JanPfenning** [JanPfenning/AdvancedSoftwareEngineeringSplit#12]
I Zentrale Regel für Abhängigkeiten
⇒ Abhängigkeiten immer von außen nach innen
I Erfordert für jede Klasse eine klare Positionierung
I Abhängigkeitspfeile gehen immer von außen nach
innen
I Aufrufpfeile können in beide Richtungen gehen

**Comment by MeNoSmartBrain** [comment]
Clean Architectur umsetzen. zeigen durch UML diagramme (Pfeile nur in einer Richtung)
