### ISSUE TITLE
10 Unit Tests

### ISSUE THREAD

**Issue by JanPfenning** [JanPfenning/AdvancedSoftwareEngineeringSplit#19]
[Nennung von 10 Unit-Tests und Beschreibung, was getestet wird]

**Comment by JanPfenning** [comment]
Unit Tests stehen in der Dokumentation, die meisten sind schon fertig implementiert

**Comment by JanPfenning** [comment]
Ein Test ist fehlerhaft, beim Testen, nicht aber beim händisch ausführen. Evtl wegen dem Ausführen einer Overwritten Method

MoneypoolToAccount() in TransferServiceTest

**Comment by MeNoSmartBrain** [comment]
Finish invoiceServiceTest
