### ISSUE TITLE
Kapitel 8: Entwurfsmuster

### ISSUE THREAD

**Issue by JanPfenning** [JanPfenning/AdvancedSoftwareEngineeringSplit#23]
[2 unterschiedliche Entwurfsmuster aus der Vorlesung (oder nach Absprache auch andere) jeweils
sinnvoll einsetzen, begründen und UML-Diagramm]

**Comment by JanPfenning** [comment]
Auf den Folien genannte Entwurfsmuster:
![image](https://user-images.githubusercontent.com/27968404/161083863-3d274fd5-2864-4053-96f7-7b8edc3b40bd.png)

**Comment by MeNoSmartBrain** [comment]
ToDo: suche verwendbare Muster; vielleicht schon manche umgesetzt, sonst einbauen --> Refactor

**Comment by JanPfenning** [comment]
Das Komposium Entwurfsmuster:
https://de.wikipedia.org/wiki/Kompositum_(Entwurfsmuster)
Ist auch von der "Gang of Four"
Das haben wir quasi bei einem Payment, welches aus transaktion und Invoice besteht

**Comment by JanPfenning** [comment]
Wenn wir gar nichts finden bauen wir eine Factory methode ein

**Comment by JanPfenning** [comment]
Bridge könnte evtl zwischen irgendein Interface und eine Implementierung eingeschoben werden
habs noch nicht 100% verstanden
https://de.wikipedia.org/wiki/Br%C3%BCcke_(Entwurfsmuster)

**Comment by JanPfenning** [comment]
Im TransFerservice werden quasi Memento-Objekte gebaut vom Typ Balance gebaut.
Die Balances werden erst aktualisiert wenn alle Checks auf den Memento-Objekten erfolgreich sind.

**Comment by JanPfenning** [comment]
Das Result-Objekt kann man auch ziemlich gut einfügen denke ich

**Comment by JanPfenning** [comment]
Bequemlichkeitsmethode (S. 195) haben wir auch eigentlich schon drin oder sind einfach einzufügen
http://www.inf.fu-berlin.de/lehre/WS02/SWT/slides4pdf/24_LE_23B.pdf

**Comment by JanPfenning** [comment]
UserRepositoryInterface könnte eine "Fassade" sein für das aufgeteilte Subsystem darunter

**Comment by JanPfenning** [comment]
Ich habe ein Memento und ein Iterator hinzugefügt - hab keine so wirklich passenden im Code vorhandenen Muster gefunden. Wenn du doch welche im Code findest oder du eine sehr passende Stelle findest, dann sag bescheid
