### ISSUE TITLE
Invoice constructor doesn't set Timestamp

### ISSUE THREAD

**Issue by MeNoSmartBrain** [JanPfenning/AdvancedSoftwareEngineeringSplit#43]
public Invoice(UUID id, Depot biller, UserAggregate recipient, Amount amount, boolean paid) {
        this.id = id;
        this.biller = biller;
        this.recipient = recipient;
        this.amount = amount;
        this.paid = paid;
    }

Is used when reading a CSVs file, but doesn't set the timestamp, so test fail

**Comment by JanPfenning** [comment]
Tests sollten nicht failen, wenn nicht explizit auf den Timestamp verglichen wird.
Im Konstruktor aktuell nicht gesetzt, da man nicht:
Timestamp.fromLong(readTimestamp)
oder änliches machen kann

**Comment by JanPfenning** [comment]
Kann aber auch durch ein Value Object Timestamp gelöst werden

**Comment by MeNoSmartBrain** [comment]
Quick Fix: Test doen't check if TImestamp is correct

Later:
Add Timestamp to constructor and ...

**Comment by MeNoSmartBrain** [comment]
Test case was not needed anymore. Issue closed
