### ISSUE TITLE
CSVreader returns no rows for mock_Data/UsersAccounts.csv

### ISSUE THREAD

**Issue by MeNoSmartBrain** [JanPfenning/AdvancedSoftwareEngineeringSplit#44]
![image](https://user-images.githubusercontent.com/65497740/162623210-e80294ae-ccf3-4f71-949a-4f5091a2d1a3.png)
![image](https://user-images.githubusercontent.com/65497740/162623246-9cb06fec-0f30-4967-a366-c1aa523b2443.png)

The CSVreader call in UserRepository doesn't return any data despite apperently having the right parameters

**Comment by JanPfenning** [comment]
Ist das während den Tests oder während der normalen ausführung?
